[tool.black]
extend-exclude = "^/src/multiple_choice/packaging"

[tool.coverage.run]
omit = [
    "src/multiple_choice/packaging/*",
]

[tool.isort]
profile = "black"
extend_skip = [
    "src/multiple_choice/packaging/",
]
